//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processor.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://Simulador.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Simulador.org/", ConfigurationName="ServiceReference.SimulacionSoap")]
    public interface SimulacionSoap {
        
        // CODEGEN: Generating message contract since element name cliente from namespace http://Simulador.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Simulador.org/CompletarCliente", ReplyAction="*")]
        Processor.ServiceReference.CompletarClienteResponse CompletarCliente(Processor.ServiceReference.CompletarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Simulador.org/CompletarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Processor.ServiceReference.CompletarClienteResponse> CompletarClienteAsync(Processor.ServiceReference.CompletarClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompletarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompletarCliente", Namespace="http://Simulador.org/", Order=0)]
        public Processor.ServiceReference.CompletarClienteRequestBody Body;
        
        public CompletarClienteRequest() {
        }
        
        public CompletarClienteRequest(Processor.ServiceReference.CompletarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Simulador.org/")]
    public partial class CompletarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Processor.ServiceReference.Cliente cliente;
        
        public CompletarClienteRequestBody() {
        }
        
        public CompletarClienteRequestBody(Processor.ServiceReference.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompletarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompletarClienteResponse", Namespace="http://Simulador.org/", Order=0)]
        public Processor.ServiceReference.CompletarClienteResponseBody Body;
        
        public CompletarClienteResponse() {
        }
        
        public CompletarClienteResponse(Processor.ServiceReference.CompletarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Simulador.org/")]
    public partial class CompletarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Processor.ServiceReference.Cliente CompletarClienteResult;
        
        public CompletarClienteResponseBody() {
        }
        
        public CompletarClienteResponseBody(Processor.ServiceReference.Cliente CompletarClienteResult) {
            this.CompletarClienteResult = CompletarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimulacionSoapChannel : Processor.ServiceReference.SimulacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimulacionSoapClient : System.ServiceModel.ClientBase<Processor.ServiceReference.SimulacionSoap>, Processor.ServiceReference.SimulacionSoap {
        
        public SimulacionSoapClient() {
        }
        
        public SimulacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimulacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimulacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimulacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Processor.ServiceReference.CompletarClienteResponse Processor.ServiceReference.SimulacionSoap.CompletarCliente(Processor.ServiceReference.CompletarClienteRequest request) {
            return base.Channel.CompletarCliente(request);
        }
        
        public Processor.ServiceReference.Cliente CompletarCliente(Processor.ServiceReference.Cliente cliente) {
            Processor.ServiceReference.CompletarClienteRequest inValue = new Processor.ServiceReference.CompletarClienteRequest();
            inValue.Body = new Processor.ServiceReference.CompletarClienteRequestBody();
            inValue.Body.cliente = cliente;
            Processor.ServiceReference.CompletarClienteResponse retVal = ((Processor.ServiceReference.SimulacionSoap)(this)).CompletarCliente(inValue);
            return retVal.Body.CompletarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Processor.ServiceReference.CompletarClienteResponse> Processor.ServiceReference.SimulacionSoap.CompletarClienteAsync(Processor.ServiceReference.CompletarClienteRequest request) {
            return base.Channel.CompletarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Processor.ServiceReference.CompletarClienteResponse> CompletarClienteAsync(Processor.ServiceReference.Cliente cliente) {
            Processor.ServiceReference.CompletarClienteRequest inValue = new Processor.ServiceReference.CompletarClienteRequest();
            inValue.Body = new Processor.ServiceReference.CompletarClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((Processor.ServiceReference.SimulacionSoap)(this)).CompletarClienteAsync(inValue);
        }
    }
}
