//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Processor.Integrador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://tellerBanco1.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Processor.Integrador.RequestDatosPersonales))]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Processor.Integrador.TipoPedido tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Processor.Integrador.TipoPedido tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDatosPersonales", Namespace="http://tellerBanco1.org/")]
    [System.SerializableAttribute()]
    public partial class RequestDatosPersonales : Processor.Integrador.Pedido {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Processor.Integrador.Cliente datosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Processor.Integrador.Cliente datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPedido", Namespace="http://tellerBanco1.org/")]
    public enum TipoPedido : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        transaccion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        retiro = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        deposito = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        datosPersonales = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tellerBanco1.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private System.Nullable<decimal> BalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://tellerBanco1.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Processor.Integrador.ResponseDatosPersonales))]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Processor.Integrador.TipoRespuesta tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Processor.Integrador.TipoRespuesta tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDatosPersonales", Namespace="http://tellerBanco1.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseDatosPersonales : Processor.Integrador.Respuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Processor.Integrador.Cliente datosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Processor.Integrador.Cliente datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRespuesta", Namespace="http://tellerBanco1.org/")]
    public enum TipoRespuesta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        confimacion = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatosPersonales = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tellerBanco1.org/", ConfigurationName="Integrador.Integrador_CoreSoap")]
    public interface Integrador_CoreSoap {
        
        // CODEGEN: Generating message contract since element name RDP from namespace http://tellerBanco1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tellerBanco1.org/Pedidosdatos", ReplyAction="*")]
        Processor.Integrador.PedidosdatosResponse Pedidosdatos(Processor.Integrador.PedidosdatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tellerBanco1.org/Pedidosdatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Processor.Integrador.PedidosdatosResponse> PedidosdatosAsync(Processor.Integrador.PedidosdatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PedidosdatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pedidosdatos", Namespace="http://tellerBanco1.org/", Order=0)]
        public Processor.Integrador.PedidosdatosRequestBody Body;
        
        public PedidosdatosRequest() {
        }
        
        public PedidosdatosRequest(Processor.Integrador.PedidosdatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tellerBanco1.org/")]
    public partial class PedidosdatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Processor.Integrador.RequestDatosPersonales RDP;
        
        public PedidosdatosRequestBody() {
        }
        
        public PedidosdatosRequestBody(Processor.Integrador.RequestDatosPersonales RDP) {
            this.RDP = RDP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PedidosdatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PedidosdatosResponse", Namespace="http://tellerBanco1.org/", Order=0)]
        public Processor.Integrador.PedidosdatosResponseBody Body;
        
        public PedidosdatosResponse() {
        }
        
        public PedidosdatosResponse(Processor.Integrador.PedidosdatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tellerBanco1.org/")]
    public partial class PedidosdatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Processor.Integrador.ResponseDatosPersonales PedidosdatosResult;
        
        public PedidosdatosResponseBody() {
        }
        
        public PedidosdatosResponseBody(Processor.Integrador.ResponseDatosPersonales PedidosdatosResult) {
            this.PedidosdatosResult = PedidosdatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Integrador_CoreSoapChannel : Processor.Integrador.Integrador_CoreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Integrador_CoreSoapClient : System.ServiceModel.ClientBase<Processor.Integrador.Integrador_CoreSoap>, Processor.Integrador.Integrador_CoreSoap {
        
        public Integrador_CoreSoapClient() {
        }
        
        public Integrador_CoreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Integrador_CoreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Integrador_CoreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Integrador_CoreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Processor.Integrador.PedidosdatosResponse Processor.Integrador.Integrador_CoreSoap.Pedidosdatos(Processor.Integrador.PedidosdatosRequest request) {
            return base.Channel.Pedidosdatos(request);
        }
        
        public Processor.Integrador.ResponseDatosPersonales Pedidosdatos(Processor.Integrador.RequestDatosPersonales RDP) {
            Processor.Integrador.PedidosdatosRequest inValue = new Processor.Integrador.PedidosdatosRequest();
            inValue.Body = new Processor.Integrador.PedidosdatosRequestBody();
            inValue.Body.RDP = RDP;
            Processor.Integrador.PedidosdatosResponse retVal = ((Processor.Integrador.Integrador_CoreSoap)(this)).Pedidosdatos(inValue);
            return retVal.Body.PedidosdatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Processor.Integrador.PedidosdatosResponse> Processor.Integrador.Integrador_CoreSoap.PedidosdatosAsync(Processor.Integrador.PedidosdatosRequest request) {
            return base.Channel.PedidosdatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Processor.Integrador.PedidosdatosResponse> PedidosdatosAsync(Processor.Integrador.RequestDatosPersonales RDP) {
            Processor.Integrador.PedidosdatosRequest inValue = new Processor.Integrador.PedidosdatosRequest();
            inValue.Body = new Processor.Integrador.PedidosdatosRequestBody();
            inValue.Body.RDP = RDP;
            return ((Processor.Integrador.Integrador_CoreSoap)(this)).PedidosdatosAsync(inValue);
        }
    }
}
