//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDenominaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDenominaciones()
        {
            this.tblInventario_Efectivo = new HashSet<tblInventario_Efectivo>();
        }
    
        public int Id { get; set; }
        public decimal Valor { get; set; }
        public int Tipo { get; set; }
        public string Moneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventario_Efectivo> tblInventario_Efectivo { get; set; }
        public virtual tblTipoDenominaciones tblTipoDenominaciones { get; set; }
    }
}
