//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventario_Efectivo
    {
        public int Id { get; set; }
        public int Caja { get; set; }
        public int Denominacion { get; set; }
        public int Cantidad { get; set; }
    
        public virtual tblCajas tblCajas { get; set; }
        public virtual tblDenominaciones tblDenominaciones { get; set; }
    }
}
