//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccion
    {
        public int Id { get; set; }
        public int Tipo { get; set; }
        public decimal Monto { get; set; }
        public string Cuenta { get; set; }
        public int Caja { get; set; }
        public int Cajero { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tblCajas tblCajas { get; set; }
        public virtual tblTipo_Transaccion tblTipo_Transaccion { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
