//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuarios()
        {
            this.tblCuadres = new HashSet<tblCuadres>();
            this.tblTransaccion = new HashSet<tblTransaccion>();
        }
    
        public int Codigo_Usuario { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public string Contraseña { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Caja { get; set; }
        public bool Activo { get; set; }
        public int Sucursal { get; set; }
    
        public virtual tblCajas tblCajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCuadres> tblCuadres { get; set; }
        public virtual tblSucursales tblSucursales { get; set; }
        public virtual tblTiposDeUsuario tblTiposDeUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransaccion> tblTransaccion { get; set; }
    }
}
